config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :plants
end

app/models/plant.rb
class Plant < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    @plant = Plant.new
    @plants = Plant.all
  end

  def create
    @plant = Plant.new(plant_params)
    if @plant.save
      redirect_to plants_path
    else
      render :index
    end
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update_attributes!(plant_params)

    redirect_to plants_path(@plant)
  end

  def destroy
    @plant = Plant.find(params[:id]).delete

    redirect_to plants_path
  end

  private
  def plant_params
    params.require(:plant).permit(:name, :size)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudPlants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/edit.html.erb
<%= form_for @plant do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :size %>
    <%= f.text_field :size %>
  </p>
<p>
  <%= f.submit 'Update plant' %>
</p>
<% end %>

app/views/plants/index.html.erb
<%= form_for @plant do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :size %>
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.submit 'Add plant' %>
  </p>
<% end %>

<% @plants.each do |plant| %>
<ul>
  <li>
    <%= link_to "#{plant.name}", plant_path(plant) %>, <%= plant.size %>
  </li>
</ul>
<% end %>

app/views/plants/show.html.erb
<ul>
  <li>
    <%= @plant.name %>, <%= @plant.size %>
  </li>
</ul>

<%= link_to 'Edit', edit_plant_path %>
<%= link_to 'Delete', plant_path, method: :delete %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Add a plant', plants_path %>